driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 512

platforms:
  - name: ubuntu-12.10
    run_list:
      - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-10.04
    run_list:
      - recipe[apt::default]
  - name: debian-7.1.0
    run_list:
      - recipe[apt::default]
  - name: centos-6.4
  - name: centos-5.9

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
  - name: source
    run_list:
      - recipe[nginx::default]
    attributes:
      nginx:
        install_method: source
  - name: upstream_repo
    run_list:
      - recipe[nginx::repo]
      - recipe[nginx::default]
    attributes:
      nginx:
        repo_source: nginx
  - name: modules
    run_list:
      - recipe[nginx::source]
    attributes:
      nginx:
        modules:
          - nginx::headers_more_module
          - nginx::http_auth_request_module
          - nginx::http_echo_module
          - nginx::http_geoip_module
          - nginx::http_gzip_static_module
          - nginx::http_realip_module
          - nginx::http_spdy_module
          - nginx::http_ssl_module
          - nginx::http_stub_status_module
          - nginx::naxsi_module
          - nginx::ngx_devel_module
          - nginx::ngx_lua_module
          - nginx::openssl_source
          - nginx::upload_progress_module
